"""empty message

Revision ID: 0d13cff3f155
Revises: ae006f84cd46
Create Date: 2025-07-19 13:27:29.388693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d13cff3f155'
down_revision: Union[str, None] = 'ae006f84cd46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_game_name_trgm', 'gamesdetails', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_gamesdetails_name'), 'gamesdetails', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gamesdetails_name'), table_name='gamesdetails')
    op.drop_index('idx_game_name_trgm', table_name='gamesdetails', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    # ### end Alembic commands ###
