"""empty message

Revision ID: 1e9b8f6d74ee
Revises: c9eb029e109a
Create Date: 2025-05-03 11:55:32.802671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e9b8f6d74ee'
down_revision: Union[str, None] = 'c9eb029e109a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_confirmation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_confirmation_token'), 'email_confirmation', ['token'], unique=False)
    op.drop_index('ix_historysteambase_id', table_name='historysteambase')
    op.drop_table('historysteambase')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historysteambase',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('snapshot_date', sa.DATE(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='historysteambase_pkey')
    )
    op.create_index('ix_historysteambase_id', 'historysteambase', ['id'], unique=False)
    op.drop_index(op.f('ix_email_confirmation_token'), table_name='email_confirmation')
    op.drop_table('email_confirmation')
    # ### end Alembic commands ###
