"""empty message

Revision ID: 22beb241aa96
Revises: c54e5880b257
Create Date: 2025-05-03 12:15:35.136705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22beb241aa96'
down_revision: Union[str, None] = 'c54e5880b257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_confirmation', sa.Column('type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_confirmation', 'type')
    # ### end Alembic commands ###
