"""empty message

Revision ID: 313fba3dd3a0
Revises: 91c92d5cf38f
Create Date: 2025-07-21 20:49:28.469117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '313fba3dd3a0'
down_revision: Union[str, None] = '91c92d5cf38f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safe_games',
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('appid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('safe_games')
    # ### end Alembic commands ###
