"""empty message

Revision ID: 43500137d61e
Revises: fdd5c51566cc
Create Date: 2025-07-09 13:09:06.974356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43500137d61e'
down_revision: Union[str, None] = 'fdd5c51566cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_steambase_appid', table_name='steambase')
    op.create_index(op.f('ix_steambase_appid'), 'steambase', ['appid'], unique=True)
    op.drop_index('ix_steambase_copy_appid', table_name='steambase_copy')
    op.create_index(op.f('ix_steambase_copy_appid'), 'steambase_copy', ['appid'], unique=True)
    op.drop_index('ix_steambase_temp_appid', table_name='steambase_temp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_steambase_temp_appid'), table_name='steambase_temp')
    op.create_index('ix_steambase_temp_appid', 'steambase_temp', ['appid'], unique=False)
    op.drop_index(op.f('ix_steambase_copy_appid'), table_name='steambase_copy')
    op.create_index('ix_steambase_copy_appid', 'steambase_copy', ['appid'], unique=False)
    op.drop_index(op.f('ix_steambase_appid'), table_name='steambase')
    op.create_index('ix_steambase_appid', 'steambase', ['appid'], unique=False)
    # ### end Alembic commands ###
