"""empty message

Revision ID: 5c151d36fb42
Revises: fcd542e7f5fa
Create Date: 2025-03-03 10:50:50.893679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c151d36fb42'
down_revision: Union[str, None] = 'fcd542e7f5fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamesdetails', sa.Column('name', sa.String(), nullable=True))
    op.add_column('gamesdetails', sa.Column('last_updated', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gamesdetails', 'last_updated')
    op.drop_column('gamesdetails', 'name')
    # ### end Alembic commands ###
