"""empty message

Revision ID: 5cbb58a258d4
Revises: 44757e25bee7
Create Date: 2025-04-01 19:04:22.796977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cbb58a258d4'
down_revision: Union[str, None] = '44757e25bee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_steambase_id', table_name='steambase')
    op.create_index(op.f('ix_steambase_appid'), 'steambase', ['appid'], unique=False)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_index(op.f('ix_steambase_appid'), table_name='steambase')
    op.create_index('ix_steambase_id', 'steambase', ['id'], unique=False)
    # ### end Alembic commands ###
