"""empty message

Revision ID: 62949cbb434b
Revises: 31220258be03
Create Date: 2025-07-29 16:42:49.866758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62949cbb434b'
down_revision: Union[str, None] = '31220258be03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_steam_base',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('update_steam_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_steam_base')
    # ### end Alembic commands ###
