"""empty message

Revision ID: 63ff6a5d4af9
Revises: 43500137d61e
Create Date: 2025-07-11 14:25:56.951000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ff6a5d4af9'
down_revision: Union[str, None] = '43500137d61e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steambase',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('appid', sa.String(), nullable=True),
    sa.Column('developer', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('positive', sa.Integer(), nullable=True),
    sa.Column('negative', sa.Integer(), nullable=True),
    sa.Column('average_forever', sa.Integer(), nullable=True),
    sa.Column('average_2weeks', sa.Integer(), nullable=True),
    sa.Column('median_forever', sa.Integer(), nullable=True),
    sa.Column('median_2weeks', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steambase_appid'), 'steambase', ['appid'], unique=True)
    op.create_table('steambase_copy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('appid', sa.String(), nullable=True),
    sa.Column('developer', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('positive', sa.Integer(), nullable=True),
    sa.Column('negative', sa.Integer(), nullable=True),
    sa.Column('average_forever', sa.Integer(), nullable=True),
    sa.Column('average_2weeks', sa.Integer(), nullable=True),
    sa.Column('median_forever', sa.Integer(), nullable=True),
    sa.Column('median_2weeks', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steambase_copy_appid'), 'steambase_copy', ['appid'], unique=True)
    op.create_table('steambase_temp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('appid', sa.String(), nullable=True),
    sa.Column('developer', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('positive', sa.Integer(), nullable=True),
    sa.Column('negative', sa.Integer(), nullable=True),
    sa.Column('average_forever', sa.Integer(), nullable=True),
    sa.Column('average_2weeks', sa.Integer(), nullable=True),
    sa.Column('median_forever', sa.Integer(), nullable=True),
    sa.Column('median_2weeks', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steambase_temp_appid'), 'steambase_temp', ['appid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_gamesdetails_steam_appid', 'gamesdetails', type_='unique')
    op.drop_index(op.f('ix_steambase_temp_appid'), table_name='steambase_temp')
    op.drop_table('steambase_temp')
    op.drop_index(op.f('ix_steambase_copy_appid'), table_name='steambase_copy')
    op.drop_table('steambase_copy')
    op.drop_index(op.f('ix_steambase_appid'), table_name='steambase')
    op.drop_table('steambase')
    # ### end Alembic commands ###
