"""empty message

Revision ID: 91c92d5cf38f
Revises: 0d13cff3f155
Create Date: 2025-07-21 15:09:30.085108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c92d5cf38f'
down_revision: Union[str, None] = '0d13cff3f155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_games',
    sa.Column('appid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('appid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_gamesdetails_steam_appid', 'gamesdetails', type_='unique')
    op.drop_table('blocked_games')
    # ### end Alembic commands ###
