"""empty message

Revision ID: acf81328eb71
Revises: 1cf7227fd915
Create Date: 2025-07-08 12:45:53.606220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf81328eb71'
down_revision: Union[str, None] = '1cf7227fd915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamesdetails', sa.Column('release_data', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gamesdetails', 'release_data')
    # ### end Alembic commands ###
