"""empty message

Revision ID: ae006f84cd46
Revises: dc0e4525a99f
Create Date: 2025-07-19 11:40:42.178298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae006f84cd46'
down_revision: Union[str, None] = 'dc0e4525a99f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamesdetails', sa.Column('trailer_url', sa.String(), nullable=True))
    op.add_column('steambase', sa.Column('ccu', sa.Integer(), nullable=True))
    op.add_column('steambase_copy', sa.Column('ccu', sa.Integer(), nullable=True))
    op.add_column('steambase_temp', sa.Column('ccu', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steambase_temp', 'ccu')
    op.drop_column('steambase_copy', 'ccu')
    op.drop_column('steambase', 'ccu')
    op.drop_column('gamesdetails', 'trailer_url')
    # ### end Alembic commands ###
