"""New table

Revision ID: ca97cd8bef43
Revises: f9718993607b
Create Date: 2025-03-21 20:46:24.289032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca97cd8bef43'
down_revision: Union[str, None] = 'f9718993607b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refreshtokens', sa.Column('delete_time', sa.Date(), nullable=True))
    op.alter_column('refreshtokens', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_refreshtokens_refresh_token'), 'refreshtokens', ['refresh_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refreshtokens_refresh_token'), table_name='refreshtokens')
    op.alter_column('refreshtokens', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('refreshtokens', 'delete_time')
    # ### end Alembic commands ###
