"""Change database

Revision ID: db4a344f911e
Revises: f3b8c6d3c320
Create Date: 2025-03-02 13:18:55.888377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db4a344f911e'
down_revision: Union[str, None] = 'f3b8c6d3c320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gamesdetails', 'developer')
    op.drop_column('gamesdetails', 'publisher')
    op.drop_column('gamesdetails', 'release_date')
    op.drop_column('gamesdetails', 'release_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamesdetails', sa.Column('release_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('gamesdetails', sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('gamesdetails', sa.Column('publisher', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('gamesdetails', sa.Column('developer', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
