"""empty message

Revision ID: dc0e4525a99f
Revises: c82878d95523
Create Date: 2025-07-12 17:09:14.335123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0e4525a99f'
down_revision: Union[str, None] = 'c82878d95523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steam_events', sa.Column('type_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'steam_events', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'steam_events', type_='unique')
    op.drop_column('steam_events', 'type_name')
    op.drop_constraint('uq_gamesdetails_steam_appid', 'gamesdetails', type_='unique')
    # ### end Alembic commands ###
