"""Add img_url to game

Revision ID: f3b8c6d3c320
Revises: b8235dae158b
Create Date: 2025-03-02 12:18:47.755036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3b8c6d3c320'
down_revision: Union[str, None] = 'b8235dae158b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamesdetails', sa.Column('img_url', sa.String(), nullable=True))
    op.drop_column('gamesdetails', 'ganres')
    op.drop_column('gamesdetails', 'categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamesdetails', sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('gamesdetails', sa.Column('ganres', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('gamesdetails', 'img_url')
    # ### end Alembic commands ###
