"""empty message

Revision ID: fcd542e7f5fa
Revises: 213216b7e4ab
Create Date: 2025-03-03 10:37:47.528839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd542e7f5fa'
down_revision: Union[str, None] = '213216b7e4ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gamesdetails_id', table_name='gamesdetails')
    op.create_index(op.f('ix_gamesdetails_steam_appid'), 'gamesdetails', ['steam_appid'], unique=True)
    op.drop_column('gamesdetails', 'name')
    op.drop_column('gamesdetails', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamesdetails', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('gamesdetails', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_gamesdetails_steam_appid'), table_name='gamesdetails')
    op.create_index('ix_gamesdetails_id', 'gamesdetails', ['id'], unique=False)
    # ### end Alembic commands ###
