"""empty message

Revision ID: fdd5c51566cc
Revises: acf81328eb71
Create Date: 2025-07-09 12:07:59.869710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdd5c51566cc'
down_revision: Union[str, None] = 'acf81328eb71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steambase_temp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('appid', sa.String(), nullable=True),
    sa.Column('developer', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('positive', sa.Integer(), nullable=True),
    sa.Column('negative', sa.Integer(), nullable=True),
    sa.Column('average_forever', sa.Integer(), nullable=True),
    sa.Column('average_2weeks', sa.Integer(), nullable=True),
    sa.Column('median_forever', sa.Integer(), nullable=True),
    sa.Column('median_2weeks', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steambase_temp_appid'), 'steambase_temp', ['appid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_gamesdetails_steam_appid', 'gamesdetails', type_='unique')
    op.drop_index(op.f('ix_steambase_temp_appid'), table_name='steambase_temp')
    op.drop_table('steambase_temp')
    # ### end Alembic commands ###
